Brusak_Project/app/form_cabinet/models.py
from .. import db

class Contact(db.Model) :
    __tablename__ = "contacts"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(15), unique=False, nullable=True)
    email = db.Column(db.String(40), unique=False, nullable=True)
    phone = db.Column(db.String(15), unique=False, nullable=True)
    subject = db.Column(db.String(15), unique=False, nullable=True)
    message = db.Column(db.Text, unique=False, nullable=True)

    def __repr__(self):
        return f"Name : {self.name}, Email: {self.email}"

Brusak_Project/app/form_cabinet/forms.py
from flask_wtf import FlaskForm  
from wtforms import StringField, SubmitField, SelectField, TextAreaField
from wtforms.validators import DataRequired, Email, Length, Regexp

class Myform(FlaskForm):
    name = StringField("Name", 
                      [DataRequired("Please enter your name."), 
                       Length(min=4, max=10, message ='Length of this field must be between 4 and 10')
                       ]
                       )
    email = StringField('Email', validators=[DataRequired("Please enter your email."), Email("Please enter correct email")])
    phone = StringField('Phone',
    validators=[Regexp('(^\+380\s?[0-9]{2}\s?[0-9]{3}\s?[0-9]{4}$)$', message='Enter correct number')])
    subject = SelectField('Subject', choices=['Mathematics', 'Biology', 'Philosophy', 'English'])
    message = TextAreaField('Message', validators=[DataRequired("Please enter message."), Length(min=0,max=500, message ='The max length of this field is 500')])
    submit = SubmitField("Send")

Brusak_Project/app/form_cabinet/__init__.py
from flask import Blueprint

cabinet_bp = Blueprint('cabinet', __name__,
                        template_folder='templates/form_cabinet')
from . import views

Brusak_Project/app/form_cabinet/views.py
from flask import render_template, request, redirect, session, url_for, flash 
from loguru import logger
from .. import db
from .models import Contact
from .forms import Myform

from . import cabinet_bp

logger.add("my.log")

@cabinet_bp.route('/contact', methods=['GET', 'POST'])
def contact():
    form = Myform()
    if form.validate_on_submit():
        session['username'] = form.name.data
        session['email'] = form.email.data
        save_to_db(form)
        logger.info(f"{form.name.data} {form.email.data} {form.phone.data} {form.subject.data} {form.message.data}")
        flash("Data sent successfully: " + session.get('username') + ' ' + session.get('email'), category = 'success')
        return redirect(url_for("cabinet.contact"))

    elif request.method == 'POST':
        flash("POST validation failed", category = 'warning')

    if(session.get('username') == None):
        return render_template('contact.html', form=form, username="Guest")
    
    form.name.data = session.get('username')
    form.email.data = session.get('email')
    return render_template('contact.html', form=form, username=session.get('username'))

@cabinet_bp.route('/delete_session')
def delete_session():
    session.pop('username', default=None)
    session.pop('email', default=None)
    return '<h1>Session deleted!</h1>'

@cabinet_bp.route('/database')
def database() :
    contacts = Contact.query.all()
    return render_template('database.html', contacts=contacts)


@cabinet_bp.route('/database/delete/<id>')
def delete_by_id(id):
    data = Contact.query.get(id)
    try:
        db.session.delete(data)
        db.session.commit()
    except :
        db.session.flush()
        db.session.rollback()   
    return redirect(url_for("cabinet.database"))

def save_to_db(form) :
    contact = Contact(
        name = form.name.data,
        email = form.email.data,
        phone = form.phone.data,
        subject = form.subject.data,
        message = form.message.data
    )
    try:
        db.session.add(contact)
        db.session.commit()
    except:
        db.session.flush()
        db.session.rollback()

Brusak_Project/app/form_cabinet/templates/form_cabinet/contact.html
{% extends "layout.html" %}
{% block title %} Contact {% endblock %}

{% block name %}

<br><h1 class="text-center"> Hi, {{username}}</h1>

{% endblock %}

{% block body %}

{% for cat, msg in get_flashed_messages(True) %}
<ul class="list-group">
    <li class="list-group-item list-group-item-{{cat}} mx-auto" style="width: 400px; margin-bottom: 30px;">{{msg}}</li>
</ul>
{%endfor %}

{% from "_render_field.html" import render_field %}

  <div class="col-6 mx-auto">

    <div class="card">

      <div class="card-header">
        <h5>WTF-Form</h5>
      </div>

      <div class="card-body">
        <form method="post">
          {{ form.csrf_token }}
          {{ render_field(form.name, class="form-control") }}
          {{ render_field(form.email, class="form-control") }}
          {{ render_field(form.phone, class="form-control") }}
          {{ render_field(form.subject, class="form-control") }}
          {{ render_field(form.message, class="form-control") }}
          {{ form.submit(class="btn btn-primary") }}
        </form>
      </div>

    </div>

  </div>

{% endblock %}

Brusak_Project/app/form_cabinet/templates/form_cabinet/database.html
{% extends 'layout.html' %}
{% block title %} Database {% endblock %}

{% block name %}
<br><h1 class="text-center">Contacts</h1>
{% endblock %}

{% block body %}
<table class="table table-hover table-bordered">
    <thead class="table-dark">
      <tr>
       <th scope="col">Id</th>
       <th scope="col">Name</th>
       <th scope="col">Email</th>
       <th scope="col">Phone</th>
       <th scope="col">Subject</th>
       <th scope="col">Message</th>
       <th scope="col">Delete</th>
      </tr>
    </thead>
    {% for data in contacts %}
    <tbody>
      <tr>
       <td>{{data.id}}</td>
       <td>{{data.name}}</td>
       <td>{{data.email}}</td>
       <td>{{data.phone}}</td>
       <td>{{data.subject}}</td>
       <td>{{data.message}}</td>
       <td><a href="{{ url_for('cabinet.delete_by_id', id=data.id) }}" type="button" class="btn btn-danger">Delete</a></td>
       </tr>
    </tbody>
    {% endfor%}
 </table>
{% endblock %}